### ISSUE TITLE
_create_branch and _create_snap_recipe missing from api

### ISSUE THREAD

**Issue by kwmonroe** [battlemidget/ogc#1]
`sync_upstream` calls a couple `_create_*` functions that are missing (`_create_branch` and `_create_snap_recipe`):

https://github.com/battlemidget/ogc/blob/master/ogc/api/snap.py#L56

I see similar non-underscored funcs, so maybe the names just need to get in sync.

**Comment by battlemidget** [comment]
This is fixed with latest sync
